version: '3.4'
services:
  database:
    image: mysql:8.0
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "amazon_scrapper"
      MYSQL_USER: "vds"
      MYSQL_PASSWORD: "passworduser"
  uploader:
    build:
      context: .
      dockerfile: ./cmd/UploadService/Dockerfile
      target: uploader
    image: vardhaman123/uploader
    restart: always
    ports:
      - 4000:4000
    environment:
      DB_URL: "vds:passworduser@tcp(database:3306)/amazon_scrapper?charset=utf8&parseTime=True&loc=Local"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - database
      - rabbitmq
    links:
      - database
      - rabbitmq
  scrapper:
    build:
      context: .
      dockerfile: ./cmd/ScrapperService/Dockerfile
      target: scrapper
    image: vardhaman123/scrapper
    restart: always
    ports:
      - 1000:1000
    environment:
      DB_URL: "vds:passworduser@tcp(database:3306)/amazon_scrapper?charset=utf8&parseTime=True&loc=Local"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - database
      - rabbitmq
    links:
      - database
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5000:5672
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"

