apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: archiver
  namespace: microservice
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: vardhaman123/archiver
          restartPolicy: OnFailure