apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: microservice
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "amazon_scrapper"
            - name: MYSQL_USER
              value: "vds"
            - name: MYSQL_PASSWORD
              value: "password"

