apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: microservice
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbName
          volumeMounts:
            - name: mysql-persistent-storage-data
              mountPath: /usr/lib/mysql/data
      volumes:
        - name: mysql-persistent-storage-data
          persistentVolumeClaim:
            claimName: mysql-pv-claim




