apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: microservice
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: database