apiVersion: v1
kind: Service
metadata:
  name: scrapper
  namespace: microservice
  labels:
    run: scrapper
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 4000
  selector:
    run: scrapper