apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper
  namespace: microservice
  labels:
    app: scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - name: scrapper
          image: vardhaman123/scrapper:latest
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dburl
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbiturl

