apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper
  namespace: microservice
  labels:
    app: scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - name: scrapper
          image: vardhaman123/scrapper:latest
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbName
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: serviceName
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: userName
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: serviceName

