apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  namespace: microservice
  labels:
    app: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - name: uploader
          image: vardhaman123/uploader:latest
          ports:
            - name: uploaerport
              containerPort: 4000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dburl
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbiturl
            - name: SERVICE_PORT
              value: "4000"